/*
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractGuiexerciceValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.anaelchardan.guiexercice.guiexercice.GuiexercicePackage.eINSTANCE);
		return result;
	}
	
}
