/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced;

import org.anaelchardan.guiexerciceadvanced.GuiexerciceAdvancedStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GuiexerciceAdvancedStandaloneSetup extends GuiexerciceAdvancedStandaloneSetupGenerated {
  public static void doSetup() {
    new GuiexerciceAdvancedStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
