/*
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice.ui.tests;

import com.google.inject.Injector;
import org.anaelchardan.guiexercice.ui.internal.GuiexerciceActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GuiexerciceUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GuiexerciceActivator.getInstance().getInjector("org.anaelchardan.guiexercice.Guiexercice");
	}

}
