/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl;

import org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class GuiexerciceAdvancedFactoryImpl extends EFactoryImpl implements GuiexerciceAdvancedFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static GuiexerciceAdvancedFactory init()
  {
    try
    {
      GuiexerciceAdvancedFactory theGuiexerciceAdvancedFactory = (GuiexerciceAdvancedFactory)EPackage.Registry.INSTANCE.getEFactory(GuiexerciceAdvancedPackage.eNS_URI);
      if (theGuiexerciceAdvancedFactory != null)
      {
        return theGuiexerciceAdvancedFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new GuiexerciceAdvancedFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GuiexerciceAdvancedFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case GuiexerciceAdvancedPackage.PROGRAM: return createProgram();
      case GuiexerciceAdvancedPackage.FRAME: return createFrame();
      case GuiexerciceAdvancedPackage.FRAME_NAME: return createFrameName();
      case GuiexerciceAdvancedPackage.CONTENT: return createContent();
      case GuiexerciceAdvancedPackage.LABEL: return createLabel();
      case GuiexerciceAdvancedPackage.BUTTON: return createButton();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Program createProgram()
  {
    ProgramImpl program = new ProgramImpl();
    return program;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Frame createFrame()
  {
    FrameImpl frame = new FrameImpl();
    return frame;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FrameName createFrameName()
  {
    FrameNameImpl frameName = new FrameNameImpl();
    return frameName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Content createContent()
  {
    ContentImpl content = new ContentImpl();
    return content;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Label createLabel()
  {
    LabelImpl label = new LabelImpl();
    return label;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Button createButton()
  {
    ButtonImpl button = new ButtonImpl();
    return button;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GuiexerciceAdvancedPackage getGuiexerciceAdvancedPackage()
  {
    return (GuiexerciceAdvancedPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static GuiexerciceAdvancedPackage getPackage()
  {
    return GuiexerciceAdvancedPackage.eINSTANCE;
  }

} //GuiexerciceAdvancedFactoryImpl
