/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl;

import java.util.Collection;

import org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Frame;
import org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.GuiexerciceAdvancedPackage;
import org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Program;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.ProgramImpl#getFrames <em>Frames</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProgramImpl extends MinimalEObjectImpl.Container implements Program
{
  /**
   * The cached value of the '{@link #getFrames() <em>Frames</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFrames()
   * @generated
   * @ordered
   */
  protected EList<Frame> frames;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProgramImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GuiexerciceAdvancedPackage.Literals.PROGRAM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Frame> getFrames()
  {
    if (frames == null)
    {
      frames = new EObjectContainmentEList<Frame>(Frame.class, this, GuiexerciceAdvancedPackage.PROGRAM__FRAMES);
    }
    return frames;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GuiexerciceAdvancedPackage.PROGRAM__FRAMES:
        return ((InternalEList<?>)getFrames()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GuiexerciceAdvancedPackage.PROGRAM__FRAMES:
        return getFrames();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GuiexerciceAdvancedPackage.PROGRAM__FRAMES:
        getFrames().clear();
        getFrames().addAll((Collection<? extends Frame>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GuiexerciceAdvancedPackage.PROGRAM__FRAMES:
        getFrames().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GuiexerciceAdvancedPackage.PROGRAM__FRAMES:
        return frames != null && !frames.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ProgramImpl
