/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice.validation;

import org.anaelchardan.guiexercice.validation.AbstractGuiexerciceValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GuiexerciceValidator extends AbstractGuiexerciceValidator {
}
