/*
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGuiexerciceScopeProvider extends DelegatingScopeProvider {
}
