/*
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GuiexerciceAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/anaelchardan/guiexercice/parser/antlr/internal/InternalGuiexercice.tokens");
	}
}
