/*
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced.ui.tests;

import com.google.inject.Injector;
import org.anaelchardan.guiexerciceadvanced.ui.internal.GuiexerciceadvancedActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GuiexerciceAdvancedUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GuiexerciceadvancedActivator.getInstance().getInjector("org.anaelchardan.guiexerciceadvanced.GuiexerciceAdvanced");
	}

}
