/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.anaelchardan.guiexercice.GuiexerciceRuntimeModule;
import org.anaelchardan.guiexercice.GuiexerciceStandaloneSetup;
import org.anaelchardan.guiexercice.ide.GuiexerciceIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GuiexerciceIdeSetup extends GuiexerciceStandaloneSetup {
  @Override
  public Injector createInjector() {
    GuiexerciceRuntimeModule _guiexerciceRuntimeModule = new GuiexerciceRuntimeModule();
    GuiexerciceIdeModule _guiexerciceIdeModule = new GuiexerciceIdeModule();
    return Guice.createInjector(Modules2.mixin(_guiexerciceRuntimeModule, _guiexerciceIdeModule));
  }
}
