/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice.ide;

import org.anaelchardan.guiexercice.ide.AbstractGuiexerciceIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GuiexerciceIdeModule extends AbstractGuiexerciceIdeModule {
}
