/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice.scoping;

import org.anaelchardan.guiexercice.scoping.AbstractGuiexerciceScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class GuiexerciceScopeProvider extends AbstractGuiexerciceScopeProvider {
}
