/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Button</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Button#getButton <em>Button</em>}</li>
 *   <li>{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Button#getTo <em>To</em>}</li>
 * </ul>
 *
 * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.GuiexerciceAdvancedPackage#getButton()
 * @model
 * @generated
 */
public interface Button extends Content
{
  /**
   * Returns the value of the '<em><b>Button</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Button</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Button</em>' attribute.
   * @see #setButton(String)
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.GuiexerciceAdvancedPackage#getButton_Button()
   * @model
   * @generated
   */
  String getButton();

  /**
   * Sets the value of the '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Button#getButton <em>Button</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Button</em>' attribute.
   * @see #getButton()
   * @generated
   */
  void setButton(String value);

  /**
   * Returns the value of the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' reference.
   * @see #setTo(FrameName)
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.GuiexerciceAdvancedPackage#getButton_To()
   * @model
   * @generated
   */
  FrameName getTo();

  /**
   * Sets the value of the '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Button#getTo <em>To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' reference.
   * @see #getTo()
   * @generated
   */
  void setTo(FrameName value);

} // Button
