/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Content</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.GuiexerciceAdvancedPackage#getContent()
 * @model
 * @generated
 */
public interface Content extends EObject
{
} // Content
