/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.GuiexerciceAdvancedFactory
 * @model kind="package"
 * @generated
 */
public interface GuiexerciceAdvancedPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "guiexerciceAdvanced";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.anaelchardan.org/guiexerciceadvanced/GuiexerciceAdvanced";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "guiexerciceAdvanced";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GuiexerciceAdvancedPackage eINSTANCE = org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.GuiexerciceAdvancedPackageImpl.init();

  /**
   * The meta object id for the '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.ProgramImpl
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.GuiexerciceAdvancedPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Frames</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__FRAMES = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.FrameImpl <em>Frame</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.FrameImpl
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.GuiexerciceAdvancedPackageImpl#getFrame()
   * @generated
   */
  int FRAME = 1;

  /**
   * The feature id for the '<em><b>Frame Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__FRAME_NAME = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__TITLE = 1;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__WIDTH = 2;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__HEIGHT = 3;

  /**
   * The feature id for the '<em><b>Contents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__CONTENTS = 4;

  /**
   * The number of structural features of the '<em>Frame</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.FrameNameImpl <em>Frame Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.FrameNameImpl
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.GuiexerciceAdvancedPackageImpl#getFrameName()
   * @generated
   */
  int FRAME_NAME = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME_NAME__NAME = 0;

  /**
   * The number of structural features of the '<em>Frame Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.ContentImpl <em>Content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.ContentImpl
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.GuiexerciceAdvancedPackageImpl#getContent()
   * @generated
   */
  int CONTENT = 3;

  /**
   * The number of structural features of the '<em>Content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.LabelImpl <em>Label</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.LabelImpl
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.GuiexerciceAdvancedPackageImpl#getLabel()
   * @generated
   */
  int LABEL = 4;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__LABEL = CONTENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Label</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_FEATURE_COUNT = CONTENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.ButtonImpl <em>Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.ButtonImpl
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.GuiexerciceAdvancedPackageImpl#getButton()
   * @generated
   */
  int BUTTON = 5;

  /**
   * The feature id for the '<em><b>Button</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__BUTTON = CONTENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__TO = CONTENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = CONTENT_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Program#getFrames <em>Frames</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Frames</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Program#getFrames()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Frames();

  /**
   * Returns the meta object for class '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Frame <em>Frame</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Frame</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Frame
   * @generated
   */
  EClass getFrame();

  /**
   * Returns the meta object for the containment reference '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Frame#getFrameName <em>Frame Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Frame Name</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Frame#getFrameName()
   * @see #getFrame()
   * @generated
   */
  EReference getFrame_FrameName();

  /**
   * Returns the meta object for the attribute '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Frame#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Frame#getTitle()
   * @see #getFrame()
   * @generated
   */
  EAttribute getFrame_Title();

  /**
   * Returns the meta object for the attribute '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Frame#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Frame#getWidth()
   * @see #getFrame()
   * @generated
   */
  EAttribute getFrame_Width();

  /**
   * Returns the meta object for the attribute '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Frame#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Frame#getHeight()
   * @see #getFrame()
   * @generated
   */
  EAttribute getFrame_Height();

  /**
   * Returns the meta object for the containment reference list '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Frame#getContents <em>Contents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Contents</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Frame#getContents()
   * @see #getFrame()
   * @generated
   */
  EReference getFrame_Contents();

  /**
   * Returns the meta object for class '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.FrameName <em>Frame Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Frame Name</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.FrameName
   * @generated
   */
  EClass getFrameName();

  /**
   * Returns the meta object for the attribute '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.FrameName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.FrameName#getName()
   * @see #getFrameName()
   * @generated
   */
  EAttribute getFrameName_Name();

  /**
   * Returns the meta object for class '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Content <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Content</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Content
   * @generated
   */
  EClass getContent();

  /**
   * Returns the meta object for class '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Label <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Label
   * @generated
   */
  EClass getLabel();

  /**
   * Returns the meta object for the attribute '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Label#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Label#getLabel()
   * @see #getLabel()
   * @generated
   */
  EAttribute getLabel_Label();

  /**
   * Returns the meta object for class '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Button <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Button
   * @generated
   */
  EClass getButton();

  /**
   * Returns the meta object for the attribute '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Button#getButton <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Button</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Button#getButton()
   * @see #getButton()
   * @generated
   */
  EAttribute getButton_Button();

  /**
   * Returns the meta object for the reference '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Button#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>To</em>'.
   * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Button#getTo()
   * @see #getButton()
   * @generated
   */
  EReference getButton_To();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GuiexerciceAdvancedFactory getGuiexerciceAdvancedFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.ProgramImpl
     * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.GuiexerciceAdvancedPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Frames</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__FRAMES = eINSTANCE.getProgram_Frames();

    /**
     * The meta object literal for the '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.FrameImpl <em>Frame</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.FrameImpl
     * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.GuiexerciceAdvancedPackageImpl#getFrame()
     * @generated
     */
    EClass FRAME = eINSTANCE.getFrame();

    /**
     * The meta object literal for the '<em><b>Frame Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FRAME__FRAME_NAME = eINSTANCE.getFrame_FrameName();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRAME__TITLE = eINSTANCE.getFrame_Title();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRAME__WIDTH = eINSTANCE.getFrame_Width();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRAME__HEIGHT = eINSTANCE.getFrame_Height();

    /**
     * The meta object literal for the '<em><b>Contents</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FRAME__CONTENTS = eINSTANCE.getFrame_Contents();

    /**
     * The meta object literal for the '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.FrameNameImpl <em>Frame Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.FrameNameImpl
     * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.GuiexerciceAdvancedPackageImpl#getFrameName()
     * @generated
     */
    EClass FRAME_NAME = eINSTANCE.getFrameName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRAME_NAME__NAME = eINSTANCE.getFrameName_Name();

    /**
     * The meta object literal for the '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.ContentImpl <em>Content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.ContentImpl
     * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.GuiexerciceAdvancedPackageImpl#getContent()
     * @generated
     */
    EClass CONTENT = eINSTANCE.getContent();

    /**
     * The meta object literal for the '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.LabelImpl <em>Label</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.LabelImpl
     * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.GuiexerciceAdvancedPackageImpl#getLabel()
     * @generated
     */
    EClass LABEL = eINSTANCE.getLabel();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LABEL__LABEL = eINSTANCE.getLabel_Label();

    /**
     * The meta object literal for the '{@link org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.ButtonImpl <em>Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.ButtonImpl
     * @see org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.impl.GuiexerciceAdvancedPackageImpl#getButton()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getButton();

    /**
     * The meta object literal for the '<em><b>Button</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BUTTON__BUTTON = eINSTANCE.getButton_Button();

    /**
     * The meta object literal for the '<em><b>To</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUTTON__TO = eINSTANCE.getButton_To();

  }

} //GuiexerciceAdvancedPackage
