/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice.ui.contentassist;

import org.anaelchardan.guiexercice.ui.contentassist.AbstractGuiexerciceProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GuiexerciceProposalProvider extends AbstractGuiexerciceProposalProvider {
}
