/*
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced.parser.antlr;

import com.google.inject.Inject;
import org.anaelchardan.guiexerciceadvanced.parser.antlr.internal.InternalGuiexerciceAdvancedParser;
import org.anaelchardan.guiexerciceadvanced.services.GuiexerciceAdvancedGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GuiexerciceAdvancedParser extends AbstractAntlrParser {

	@Inject
	private GuiexerciceAdvancedGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGuiexerciceAdvancedParser createParser(XtextTokenStream stream) {
		return new InternalGuiexerciceAdvancedParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public GuiexerciceAdvancedGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GuiexerciceAdvancedGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
