/*
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GuiexerciceAdvancedAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/anaelchardan/guiexerciceadvanced/parser/antlr/internal/InternalGuiexerciceAdvanced.tokens");
	}
}
