/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice.guiexercice;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Frame</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.anaelchardan.guiexercice.guiexercice.Frame#getName <em>Name</em>}</li>
 *   <li>{@link org.anaelchardan.guiexercice.guiexercice.Frame#getTitle <em>Title</em>}</li>
 *   <li>{@link org.anaelchardan.guiexercice.guiexercice.Frame#getWidth <em>Width</em>}</li>
 *   <li>{@link org.anaelchardan.guiexercice.guiexercice.Frame#getHeight <em>Height</em>}</li>
 *   <li>{@link org.anaelchardan.guiexercice.guiexercice.Frame#getContents <em>Contents</em>}</li>
 * </ul>
 *
 * @see org.anaelchardan.guiexercice.guiexercice.GuiexercicePackage#getFrame()
 * @model
 * @generated
 */
public interface Frame extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.anaelchardan.guiexercice.guiexercice.GuiexercicePackage#getFrame_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.anaelchardan.guiexercice.guiexercice.Frame#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Title</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see org.anaelchardan.guiexercice.guiexercice.GuiexercicePackage#getFrame_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link org.anaelchardan.guiexercice.guiexercice.Frame#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Width</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Width</em>' attribute.
   * @see #setWidth(int)
   * @see org.anaelchardan.guiexercice.guiexercice.GuiexercicePackage#getFrame_Width()
   * @model
   * @generated
   */
  int getWidth();

  /**
   * Sets the value of the '{@link org.anaelchardan.guiexercice.guiexercice.Frame#getWidth <em>Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Width</em>' attribute.
   * @see #getWidth()
   * @generated
   */
  void setWidth(int value);

  /**
   * Returns the value of the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Height</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Height</em>' attribute.
   * @see #setHeight(int)
   * @see org.anaelchardan.guiexercice.guiexercice.GuiexercicePackage#getFrame_Height()
   * @model
   * @generated
   */
  int getHeight();

  /**
   * Sets the value of the '{@link org.anaelchardan.guiexercice.guiexercice.Frame#getHeight <em>Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Height</em>' attribute.
   * @see #getHeight()
   * @generated
   */
  void setHeight(int value);

  /**
   * Returns the value of the '<em><b>Contents</b></em>' containment reference list.
   * The list contents are of type {@link org.anaelchardan.guiexercice.guiexercice.Content}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Contents</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contents</em>' containment reference list.
   * @see org.anaelchardan.guiexercice.guiexercice.GuiexercicePackage#getFrame_Contents()
   * @model containment="true"
   * @generated
   */
  EList<Content> getContents();

} // Frame
