/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice.guiexercice;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.anaelchardan.guiexercice.guiexercice.GuiexerciceFactory
 * @model kind="package"
 * @generated
 */
public interface GuiexercicePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "guiexercice";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.anaelchardan.org/guiexercice/Guiexercice";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "guiexercice";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GuiexercicePackage eINSTANCE = org.anaelchardan.guiexercice.guiexercice.impl.GuiexercicePackageImpl.init();

  /**
   * The meta object id for the '{@link org.anaelchardan.guiexercice.guiexercice.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.anaelchardan.guiexercice.guiexercice.impl.ProgramImpl
   * @see org.anaelchardan.guiexercice.guiexercice.impl.GuiexercicePackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Frame</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__FRAME = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.anaelchardan.guiexercice.guiexercice.impl.FrameImpl <em>Frame</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.anaelchardan.guiexercice.guiexercice.impl.FrameImpl
   * @see org.anaelchardan.guiexercice.guiexercice.impl.GuiexercicePackageImpl#getFrame()
   * @generated
   */
  int FRAME = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__NAME = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__TITLE = 1;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__WIDTH = 2;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__HEIGHT = 3;

  /**
   * The feature id for the '<em><b>Contents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME__CONTENTS = 4;

  /**
   * The number of structural features of the '<em>Frame</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRAME_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.anaelchardan.guiexercice.guiexercice.impl.ContentImpl <em>Content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.anaelchardan.guiexercice.guiexercice.impl.ContentImpl
   * @see org.anaelchardan.guiexercice.guiexercice.impl.GuiexercicePackageImpl#getContent()
   * @generated
   */
  int CONTENT = 2;

  /**
   * The number of structural features of the '<em>Content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.anaelchardan.guiexercice.guiexercice.impl.LabelImpl <em>Label</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.anaelchardan.guiexercice.guiexercice.impl.LabelImpl
   * @see org.anaelchardan.guiexercice.guiexercice.impl.GuiexercicePackageImpl#getLabel()
   * @generated
   */
  int LABEL = 3;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__LABEL = CONTENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Label</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_FEATURE_COUNT = CONTENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.anaelchardan.guiexercice.guiexercice.impl.ButtonImpl <em>Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.anaelchardan.guiexercice.guiexercice.impl.ButtonImpl
   * @see org.anaelchardan.guiexercice.guiexercice.impl.GuiexercicePackageImpl#getButton()
   * @generated
   */
  int BUTTON = 4;

  /**
   * The feature id for the '<em><b>Button</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__BUTTON = CONTENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = CONTENT_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.anaelchardan.guiexercice.guiexercice.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.anaelchardan.guiexercice.guiexercice.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference '{@link org.anaelchardan.guiexercice.guiexercice.Program#getFrame <em>Frame</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Frame</em>'.
   * @see org.anaelchardan.guiexercice.guiexercice.Program#getFrame()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Frame();

  /**
   * Returns the meta object for class '{@link org.anaelchardan.guiexercice.guiexercice.Frame <em>Frame</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Frame</em>'.
   * @see org.anaelchardan.guiexercice.guiexercice.Frame
   * @generated
   */
  EClass getFrame();

  /**
   * Returns the meta object for the attribute '{@link org.anaelchardan.guiexercice.guiexercice.Frame#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.anaelchardan.guiexercice.guiexercice.Frame#getName()
   * @see #getFrame()
   * @generated
   */
  EAttribute getFrame_Name();

  /**
   * Returns the meta object for the attribute '{@link org.anaelchardan.guiexercice.guiexercice.Frame#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.anaelchardan.guiexercice.guiexercice.Frame#getTitle()
   * @see #getFrame()
   * @generated
   */
  EAttribute getFrame_Title();

  /**
   * Returns the meta object for the attribute '{@link org.anaelchardan.guiexercice.guiexercice.Frame#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see org.anaelchardan.guiexercice.guiexercice.Frame#getWidth()
   * @see #getFrame()
   * @generated
   */
  EAttribute getFrame_Width();

  /**
   * Returns the meta object for the attribute '{@link org.anaelchardan.guiexercice.guiexercice.Frame#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see org.anaelchardan.guiexercice.guiexercice.Frame#getHeight()
   * @see #getFrame()
   * @generated
   */
  EAttribute getFrame_Height();

  /**
   * Returns the meta object for the containment reference list '{@link org.anaelchardan.guiexercice.guiexercice.Frame#getContents <em>Contents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Contents</em>'.
   * @see org.anaelchardan.guiexercice.guiexercice.Frame#getContents()
   * @see #getFrame()
   * @generated
   */
  EReference getFrame_Contents();

  /**
   * Returns the meta object for class '{@link org.anaelchardan.guiexercice.guiexercice.Content <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Content</em>'.
   * @see org.anaelchardan.guiexercice.guiexercice.Content
   * @generated
   */
  EClass getContent();

  /**
   * Returns the meta object for class '{@link org.anaelchardan.guiexercice.guiexercice.Label <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label</em>'.
   * @see org.anaelchardan.guiexercice.guiexercice.Label
   * @generated
   */
  EClass getLabel();

  /**
   * Returns the meta object for the attribute '{@link org.anaelchardan.guiexercice.guiexercice.Label#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see org.anaelchardan.guiexercice.guiexercice.Label#getLabel()
   * @see #getLabel()
   * @generated
   */
  EAttribute getLabel_Label();

  /**
   * Returns the meta object for class '{@link org.anaelchardan.guiexercice.guiexercice.Button <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button</em>'.
   * @see org.anaelchardan.guiexercice.guiexercice.Button
   * @generated
   */
  EClass getButton();

  /**
   * Returns the meta object for the attribute '{@link org.anaelchardan.guiexercice.guiexercice.Button#getButton <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Button</em>'.
   * @see org.anaelchardan.guiexercice.guiexercice.Button#getButton()
   * @see #getButton()
   * @generated
   */
  EAttribute getButton_Button();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GuiexerciceFactory getGuiexerciceFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.anaelchardan.guiexercice.guiexercice.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.anaelchardan.guiexercice.guiexercice.impl.ProgramImpl
     * @see org.anaelchardan.guiexercice.guiexercice.impl.GuiexercicePackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Frame</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__FRAME = eINSTANCE.getProgram_Frame();

    /**
     * The meta object literal for the '{@link org.anaelchardan.guiexercice.guiexercice.impl.FrameImpl <em>Frame</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.anaelchardan.guiexercice.guiexercice.impl.FrameImpl
     * @see org.anaelchardan.guiexercice.guiexercice.impl.GuiexercicePackageImpl#getFrame()
     * @generated
     */
    EClass FRAME = eINSTANCE.getFrame();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRAME__NAME = eINSTANCE.getFrame_Name();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRAME__TITLE = eINSTANCE.getFrame_Title();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRAME__WIDTH = eINSTANCE.getFrame_Width();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRAME__HEIGHT = eINSTANCE.getFrame_Height();

    /**
     * The meta object literal for the '<em><b>Contents</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FRAME__CONTENTS = eINSTANCE.getFrame_Contents();

    /**
     * The meta object literal for the '{@link org.anaelchardan.guiexercice.guiexercice.impl.ContentImpl <em>Content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.anaelchardan.guiexercice.guiexercice.impl.ContentImpl
     * @see org.anaelchardan.guiexercice.guiexercice.impl.GuiexercicePackageImpl#getContent()
     * @generated
     */
    EClass CONTENT = eINSTANCE.getContent();

    /**
     * The meta object literal for the '{@link org.anaelchardan.guiexercice.guiexercice.impl.LabelImpl <em>Label</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.anaelchardan.guiexercice.guiexercice.impl.LabelImpl
     * @see org.anaelchardan.guiexercice.guiexercice.impl.GuiexercicePackageImpl#getLabel()
     * @generated
     */
    EClass LABEL = eINSTANCE.getLabel();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LABEL__LABEL = eINSTANCE.getLabel_Label();

    /**
     * The meta object literal for the '{@link org.anaelchardan.guiexercice.guiexercice.impl.ButtonImpl <em>Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.anaelchardan.guiexercice.guiexercice.impl.ButtonImpl
     * @see org.anaelchardan.guiexercice.guiexercice.impl.GuiexercicePackageImpl#getButton()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getButton();

    /**
     * The meta object literal for the '<em><b>Button</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BUTTON__BUTTON = eINSTANCE.getButton_Button();

  }

} //GuiexercicePackage
