/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice.guiexercice;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Label</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.anaelchardan.guiexercice.guiexercice.Label#getLabel <em>Label</em>}</li>
 * </ul>
 *
 * @see org.anaelchardan.guiexercice.guiexercice.GuiexercicePackage#getLabel()
 * @model
 * @generated
 */
public interface Label extends Content
{
  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Label</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(String)
   * @see org.anaelchardan.guiexercice.guiexercice.GuiexercicePackage#getLabel_Label()
   * @model
   * @generated
   */
  String getLabel();

  /**
   * Sets the value of the '{@link org.anaelchardan.guiexercice.guiexercice.Label#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(String value);

} // Label
