/*
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGuiexerciceAdvancedScopeProvider extends DelegatingScopeProvider {
}
