/*
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Button;
import org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Frame;
import org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.FrameName;
import org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.GuiexerciceAdvancedPackage;
import org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Label;
import org.anaelchardan.guiexerciceadvanced.guiexerciceAdvanced.Program;
import org.anaelchardan.guiexerciceadvanced.services.GuiexerciceAdvancedGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class GuiexerciceAdvancedSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private GuiexerciceAdvancedGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == GuiexerciceAdvancedPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case GuiexerciceAdvancedPackage.BUTTON:
				sequence_Button(context, (Button) semanticObject); 
				return; 
			case GuiexerciceAdvancedPackage.FRAME:
				sequence_Frame(context, (Frame) semanticObject); 
				return; 
			case GuiexerciceAdvancedPackage.FRAME_NAME:
				sequence_FrameName(context, (FrameName) semanticObject); 
				return; 
			case GuiexerciceAdvancedPackage.LABEL:
				sequence_Label(context, (Label) semanticObject); 
				return; 
			case GuiexerciceAdvancedPackage.PROGRAM:
				sequence_Program(context, (Program) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Content returns Button
	 *     Button returns Button
	 *
	 * Constraint:
	 *     (button=STRING to=[FrameName|ID])
	 */
	protected void sequence_Button(ISerializationContext context, Button semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GuiexerciceAdvancedPackage.Literals.BUTTON__BUTTON) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GuiexerciceAdvancedPackage.Literals.BUTTON__BUTTON));
			if (transientValues.isValueTransient(semanticObject, GuiexerciceAdvancedPackage.Literals.BUTTON__TO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GuiexerciceAdvancedPackage.Literals.BUTTON__TO));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getButtonAccess().getButtonSTRINGTerminalRuleCall_2_0(), semanticObject.getButton());
		feeder.accept(grammarAccess.getButtonAccess().getToFrameNameIDTerminalRuleCall_4_0_1(), semanticObject.eGet(GuiexerciceAdvancedPackage.Literals.BUTTON__TO, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     FrameName returns FrameName
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_FrameName(ISerializationContext context, FrameName semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GuiexerciceAdvancedPackage.Literals.FRAME_NAME__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GuiexerciceAdvancedPackage.Literals.FRAME_NAME__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFrameNameAccess().getNameIDTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Frame returns Frame
	 *
	 * Constraint:
	 *     (frameName=FrameName (title=STRING | width=INT | height=INT | contents+=Content)*)
	 */
	protected void sequence_Frame(ISerializationContext context, Frame semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Content returns Label
	 *     Label returns Label
	 *
	 * Constraint:
	 *     label=STRING
	 */
	protected void sequence_Label(ISerializationContext context, Label semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GuiexerciceAdvancedPackage.Literals.LABEL__LABEL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GuiexerciceAdvancedPackage.Literals.LABEL__LABEL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLabelAccess().getLabelSTRINGTerminalRuleCall_2_0(), semanticObject.getLabel());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Program returns Program
	 *
	 * Constraint:
	 *     frames+=Frame+
	 */
	protected void sequence_Program(ISerializationContext context, Program semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
