/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice;

import org.anaelchardan.guiexercice.AbstractGuiexerciceRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GuiexerciceRuntimeModule extends AbstractGuiexerciceRuntimeModule {
}
