/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice;

import org.anaelchardan.guiexercice.GuiexerciceStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GuiexerciceStandaloneSetup extends GuiexerciceStandaloneSetupGenerated {
  public static void doSetup() {
    new GuiexerciceStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
