/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice.guiexercice.impl;

import org.anaelchardan.guiexercice.guiexercice.Content;
import org.anaelchardan.guiexercice.guiexercice.GuiexercicePackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Content</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ContentImpl extends MinimalEObjectImpl.Container implements Content
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ContentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GuiexercicePackage.Literals.CONTENT;
  }

} //ContentImpl
