/*
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced.ide


/**
 * Use this class to register ide components.
 */
class GuiexerciceAdvancedIdeModule extends AbstractGuiexerciceAdvancedIdeModule {
}
