/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexercice.ui;

import org.anaelchardan.guiexercice.ui.AbstractGuiexerciceUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GuiexerciceUiModule extends AbstractGuiexerciceUiModule {
  public GuiexerciceUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
