/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.anaelchardan.guiexerciceadvanced.GuiexerciceAdvancedRuntimeModule;
import org.anaelchardan.guiexerciceadvanced.GuiexerciceAdvancedStandaloneSetup;
import org.anaelchardan.guiexerciceadvanced.ide.GuiexerciceAdvancedIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GuiexerciceAdvancedIdeSetup extends GuiexerciceAdvancedStandaloneSetup {
  @Override
  public Injector createInjector() {
    GuiexerciceAdvancedRuntimeModule _guiexerciceAdvancedRuntimeModule = new GuiexerciceAdvancedRuntimeModule();
    GuiexerciceAdvancedIdeModule _guiexerciceAdvancedIdeModule = new GuiexerciceAdvancedIdeModule();
    return Guice.createInjector(Modules2.mixin(_guiexerciceAdvancedRuntimeModule, _guiexerciceAdvancedIdeModule));
  }
}
