/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced.ide;

import org.anaelchardan.guiexerciceadvanced.ide.AbstractGuiexerciceAdvancedIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GuiexerciceAdvancedIdeModule extends AbstractGuiexerciceAdvancedIdeModule {
}
