/**
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced.scoping;

import org.anaelchardan.guiexerciceadvanced.scoping.AbstractGuiexerciceAdvancedScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class GuiexerciceAdvancedScopeProvider extends AbstractGuiexerciceAdvancedScopeProvider {
}
