/*
 * generated by Xtext 2.12.0
 */
package org.anaelchardan.guiexerciceadvanced.ui;

import com.google.inject.Injector;
import org.anaelchardan.guiexerciceadvanced.ui.internal.GuiexerciceadvancedActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GuiexerciceAdvancedExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GuiexerciceadvancedActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GuiexerciceadvancedActivator.getInstance().getInjector(GuiexerciceadvancedActivator.ORG_ANAELCHARDAN_GUIEXERCICEADVANCED_GUIEXERCICEADVANCED);
	}
	
}
